import { USER_ROLES } from "./userRoles.js";

export const RBAC_POLICIES = Object.freeze({
  DASHBOARD_VIEW: [USER_ROLES.VIEWER, USER_ROLES.ANALYST, USER_ROLES.ADMIN],
  RECORDS_VIEW: [USER_ROLES.ANALYST, USER_ROLES.ADMIN],
  RECORDS_MANAGE: [USER_ROLES.ADMIN],
  USERS_MANAGE: [USER_ROLES.ADMIN],
});
